const BASE_URL = "https://staging.kooyla.com/"
export const BASE_URL_IMAGE = "https://staging.kooyla.com/images/"

export const URL = "http://kooyla.com/"
export const URL_FAQ = BASE_URL + "master/faq"
export const URL_LOGIN = BASE_URL + "login"
export const URL_DAFTAR = BASE_URL + "register"
export const URL_RESET_PASSWORD = BASE_URL + "reset"
export const URL_USER = BASE_URL + "users/"
export const URL_KATEGORI = BASE_URL + "master/category/top"
export const URL_BLOG_KATEGORI = BASE_URL + "artikel/kategori/"
export const URL_BLOG = BASE_URL + "artikel?q="
export const DETAIL_BLOG = BASE_URL + "artikel/"
export const URL_PROFIL_BY_ID = BASE_URL + "users/profile/by/"